#!/usr/bin/env ruby

require 'optparse'
require 'json'

template = {}

OptionParser.new do |opts|
  opts.banner = "Usage: track [template]"

  opts.on("-p", "--project PROJECT_NAME", "Project name") do |project|
    template["project"] = project
  end

  opts.on("-t", "--time TIME", Integer, "Time spent (in hours)") do |time|
    template[:time] = time
  end

  opts.on("-a", "--activity ACTIVITY", "Type of activity") do |activity|
    template[:activity] = activity
  end
end.parse!

puts `git commit --allow-empty -m '#{template.to_json}'`
